### ISSUE TITLE
[SUGGESTION] Toggle sneak keybind

### ISSUE THREAD

**Issue by srnyx** [BeetMacol/toggle-toggle#2]
Not sure what to title this. But, I was looking for a mod that added a keybind to instantly toggle sneak instead of:
1. Click switch keybind (set sneak to "toggle")
2. Click sneak keybind
3. Do whatever you need that requires sneaking
4. Click switch keybind (set sneak to "hold")
5. Click sneak keybind

So, instead, I want:
1. Click toggle sneak keybind (you are now toggle sneaked)
2. Do whatever you need that requires sneaking
3. Click toggle sneak keybind (you are now untoggle sneaked)

Obviously, I don't want you to change the entire concept of the mod.
But maybe just 2 extra keybinds (or just sneak) would be amazing.

**Comment by srnyx** [comment]
Oh, also, it'd be nice if it unsneaked when opening a GUI (like inventory, chests, etc...) so that it isn't considered cheating on servers.
*Or just a setting to disable it.*

**Comment by BeetMacol** [comment]
> Oh, also, it'd be nice if it unsneaked when opening a GUI (like inventory, chests, etc...) so that it isn't considered cheating on servers. _Or just a setting to disable it._

Users who always play with sneak set to toggle, will always have that advantage, and that even works in vanilla Minecraft. That's one of the biggest reasons I made this mod, to make it fair for users that don't use toggle sneak normally.

**Comment by BeetMacol** [comment]
> Not sure what to title this. But, I was looking for a mod that added a keybind to instantly toggle sneak instead of:
> 
>     1. Click switch keybind (set sneak to "toggle")
> 
>     2. Click sneak keybind
> 
>     3. Do whatever you need that requires sneaking
> 
>     4. Click switch keybind (set sneak to "hold")
> 
>     5. Click sneak keybind
> 
> 
> So, instead, I want:
> 
>     1. Click toggle sneak keybind (you are now toggle sneaked)
> 
>     2. Do whatever you need that requires sneaking
> 
>     3. Click toggle sneak keybind (you are now untoggle sneaked)
> 
> 
> Obviously, I don't want you to change the entire concept of the mod. But maybe just 2 extra keybinds (or just sneak) would be amazing.

Well that's not what the mod is meant to do. The mod doesn't introduce new mechanic to the game, it just adds two keybinds that change those settings located in the vanilla controls menu. Separate toggle key won't be implemented in the mod.

**Comment by srnyx** [comment]
> that even works in vanilla Minecraft

Just confirmed it does... wow. Should've never 100% trusted Hypixel forums smh

> Well that's not what the mod is meant to do. The mod doesn't introduce new mechanic to the game, it just adds two keybinds that change those settings located in the vanilla controls menu. Separate toggle key won't be implemented in the mod.

Alright. Well now that I know opening chests while staying AFK is a vanilla mechanic I can just use the mod I was using before.

Thank you!

**Comment by BeetMacol** [comment]
> > that even works in vanilla Minecraft
> 
> Just confirmed it does... wow. Should've never 100% trusted Hypixel forums smh
> 
> > Well that's not what the mod is meant to do. The mod doesn't introduce new mechanic to the game, it just adds two keybinds that change those settings located in the vanilla controls menu. Separate toggle key won't be implemented in the mod.
> 
> Alright. Well now that I know opening chests while staying AFK is a vanilla mechanic I can just use the mod I was using before.
> 
> Thank you!

Wow you answered quickly, sorry for not responding to your issue for two months but I had a break from Minecraft modding and I wasn't taking care of this repo. 

Thank you for being a fair Minecraft player and have fun with playing the game.
